version: "3"
services:
  directus:
    image: directus/directus:10.12.1
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      SECRET: "pBo4E!XetF@P"
      ADMIN_EMAIL: "heemskerk.uva@gmail.com"
      ADMIN_PASSWORD: "Michae1!"
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
      WEBSOCKETS_ENABLED: "true"
      CORS_ENABLED: 'true'
      CORS_ORIGIN: 'true'
      